(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},da=ca(this),ea=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var g=a[d];if(!(g in c))break a;c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}},fa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},e;
if("function"==typeof Object.setPrototypeOf)e=Object.setPrototypeOf;else{var l;a:{var ha={a:!0},m={};try{m.__proto__=ha;l=m.a;break a}catch(a){}l=!1}e=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var n=e;
ea("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var g=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)g.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)g.push(c.call(d,b[h],h));return g}});var p=this||self,q=function(a){return a};var r;a:{var t=p.navigator;if(t){var u=t.userAgent;if(u){r=u;break a}}r=""};var ia=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in d&&b.call(void 0,d[g],g,a))return!0;return!1};var v={},w=null;var ja="function"===typeof Uint8Array;function x(a){return null!==a&&"object"===typeof a&&a.constructor===Object}function ka(a,b){if(null!=a)return Array.isArray(a)||x(a)?la(a,b):b(a)}function la(a,b){if(Array.isArray(a)){for(var c=Array(a.length),d=0;d<a.length;d++)c[d]=ka(a[d],b);Array.isArray(a)&&a.o&&y(c);return c}c={};for(d in a)c[d]=ka(a[d],b);return c}
function ma(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(ja&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!w){w={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],g=0;5>g;g++){var f=c.concat(d[g].split(""));v[g]=f;for(var h=0;h<f.length;h++){var k=f[h];void 0===w[k]&&(w[k]=h)}}}b=v[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(g=f=0;f<a.length-2;f+=3){var A=a[f],B=a[f+1];
k=a[f+2];h=b[A>>2];A=b[(A&3)<<4|B>>4];B=b[(B&15)<<2|k>>6];k=b[k&63];c[g++]=h+A+B+k}h=0;k=d;switch(a.length-f){case 2:h=a[f+1],k=b[(h&15)<<2]||d;case 1:a=a[f],c[g]=b[a>>2]+b[(a&3)<<4|h>>4]+k+d}a=c.join("")}return a;default:return a}}var na={o:{value:!0,configurable:!0}},y=function(a){Array.isArray(a)&&!Object.isFrozen(a)&&Object.defineProperties(a,na);return a},z;var oa;var C=function(a,b,c){var d=oa;oa=null;a||(a=d);d=this.constructor.C;a||(a=d?[d]:[]);this.h=(d?0:-1)-(this.constructor.B||0);this.g=a;a:{d=this.g.length;a=d-1;if(d&&(d=this.g[a],x(d))){this.j=a-this.h;this.i=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.h),this.i=null):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.j?(a+=this.h,(d=this.g[a])?y(d):this.g[a]=pa):(qa(this),(d=this.i[a])?y(d):this.i[a]=pa)},pa=Object.freeze(y([])),qa=function(a){var b=a.j+a.h;a.g[b]||(a.i=
a.g[b]={})},D=function(a,b,c){var d;(void 0===d?0:d)||b>=a.j?(qa(a),a.i[b]=c):a.g[b+a.h]=c;return a};C.prototype.toJSON=function(){var a=this.g;return z?a:la(a,ma)};function ra(a,b){return ma(b)}C.prototype.toString=function(){return this.g.toString()};var E=function(a){C.call(this,a,-1,sa)};E.prototype=fa(C.prototype);E.prototype.constructor=E;if(n)n(E,C);else for(var F in C)if("prototype"!=F)if(Object.defineProperties){var ta=Object.getOwnPropertyDescriptor(C,F);ta&&Object.defineProperty(E,F,ta)}else E[F]=C[F];var sa=[6];var G,ua=function(){if(void 0===G){var a=null,b=p.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:q,createScript:q,createScriptURL:q})}catch(c){p.console&&p.console.error(c.message)}G=a}else G=a}return G};var H=function(a,b){this.g=b===va?a:""};H.prototype.toString=function(){return this.g+""};var va={};var wa={},I=function(a,b,c){this.g=c===wa?a:""};I.prototype.toString=function(){return this.g.toString()};/*

 SPDX-License-Identifier: Apache-2.0
*/
function xa(a){return a instanceof I&&a.constructor===I?a.g:"type_error:SafeHtml"};function ya(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=a.write;var g=d.apply;c=c.map(xa);if(!(c instanceof Array)){var f="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];c=f?f.call(c):{next:aa(c)};for(var h=[];!(f=c.next()).done;)h.push(f.value);c=h}g.call(d,a,c)};var Ba=function(a,b){if(!za()){var c=Math.random();if(c<b)return c=Aa(),a[Math.floor(c*a.length)]}return null},Aa=function(){if(!p.crypto)return Math.random();try{var a=new Uint32Array(1);p.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},za=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return ia(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],Ca)||1E-4>Math.random()}),Ca=function(a){return-1!=r.indexOf(a)};var Da="platform platformVersion architecture model uaFullVersion bitness".split(" "),Ea=function(){return p.navigator&&p.navigator.userAgentData&&"function"===typeof p.navigator.userAgentData.getHighEntropyValues?p.navigator.userAgentData.getHighEntropyValues(Da).then(function(a){var b=new E;b=D(b,1,a.platform);b=D(b,2,a.platformVersion);b=D(b,3,a.architecture);b=D(b,4,a.model);b=D(b,5,a.uaFullVersion);return D(b,9,a.bitness)}):null};var Fa=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(d){}return!0}(p,!1)?"https:":"http:",Ga={},Ha=(Ga[1]="Ax15QOERqai2A5XWrDY38Eg07xh2T0pkhpDPJuDlxr7D2Ka8wHvklgK7tTPZOnT+8H31lwHto5JpvYV8jRn1WgIAAACceyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXRhZ3NlcnZpY2VzLmNvbTo0NDMiLCJmZWF0dXJlIjoiQ29udmVyc2lvbk1lYXN1cmVtZW50IiwiZXhwaXJ5IjoxNjM0MDgzMTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlLCJ1c2FnZSI6InN1YnNldCJ9",
Ga);var Ia={A:1,s:4,u:5,v:12},J={m:"40004006",l:"40004007"};function Ja(){return{1:.5,4:.02,5:.001,12:.001}}function Ka(){var a=La,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;for(var c in Ia)if(b=a[Ia[c]],"number"!==typeof b||0>b||1<b)return!1;return!0};function Ma(){var a=p.dcmads;if(null!=a.eids)return a.eids;var b=p.navigator;return b.connection&&b.connection.saveData?(a=Ba([J.m,J.l],a.expts[4]))?"4|"+a:"":""}function Na(){if(!p.dcmads.uach){var a=Ea();a&&a.then(function(b){var c=p.dcmads;a:{z=!0;try{var d=JSON.stringify(b.toJSON(),ra);break a}finally{z=!1}d=void 0}c.uach=d})}};try{p.dcmads=p.dcmads||{};p.dcmads.startTime=(new Date).getTime();var Oa=p.dcmads,K=p.dcmads.version,L={loader:235};if(K)if(L.experiment=K.experiment,81==K.number||"p"==K.number)L.number=81;else if(81==K.number||"c"==K.number)L.number=81;if(!L.number){var Pa=Ba([81,81],0);L.experiment=!!Pa;L.number=Pa||81}Oa.version=L;var Qa=p.dcmads,Ra,La=p.dcmads.expts,M;M=void 0===M?Ja:M;Ra=Ka()?La:M();Qa.expts=Ra;p.dcmads.eids=Ma();p.dcmads.ots=Ha;Na();var Sa="4|"+J.l,N,Ta=p.dcmads.version,Ua=Ta.number,Va="";
Ta.experiment&&81==Ua&&(Va="?rxp=81x81");var Wa="impl_v"+Ua+".js"+Va,Xa=p.document,Ya=Xa.currentScript||Array.from(Xa.getElementsByTagName("script")).pop();N=(0==(Ya&&Ya.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+Wa;if(p.dcmads.eids===Sa){var Za=p.document,O,$a=ua(),ab=$a?$a.createScriptURL(N):N;O=new H(ab,va);var P,Q=Za,R="SCRIPT";Q=void 0===Q?document:Q;R=String(R);var bb;"application/xhtml+xml"===(null==(bb=Q)?void 0:bb.contentType)&&(R=R.toLowerCase());P=Q.createElement(R);
P.src=O instanceof H&&O.constructor===H?O.g:"type_error:TrustedResourceUrl";var cb,S,db=(P.ownerDocument&&P.ownerDocument.defaultView||window).document,T=null===(S=db.querySelector)||void 0===S?void 0:S.call(db,"script[nonce]");(cb=T?T.nonce||T.getAttribute("nonce")||"":"")&&P.setAttribute("nonce",cb);var U=Za.getElementsByTagName("script")[0];U&&U.parentNode&&U.parentNode.insertBefore(P,U)}else{var eb=p.document,fb='<script src="'+N+'">\x3c/script>',gb=ua(),hb=gb?gb.createHTML(fb):fb;ya(eb,new I(hb,
null,wa))}}catch(a){if(.01>Math.random()){var V="";try{var W,X=a.toString();a.name&&-1==X.indexOf(a.name)&&(X+=": "+a.name);a.message&&-1==X.indexOf(a.message)&&(X+=": "+a.message);if(a.stack){var Y=a.stack,Z=X;try{-1==Y.indexOf(Z)&&(Y=Z+"\n"+Y);for(var ib;Y!=ib;)ib=Y,Y=Y.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");X=Y.replace(/\n */g,"\n")}catch(b){X=Z}}W=X;W=W.substring(0,1024);V=encodeURIComponent(W)}catch(b){V="extr"}var jb=p.dcmads.eids,kb=document.createElement("img");kb.src=Fa+
"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=235&context=554"+((jb?"&eids="+jb:"")+"&msg="+V);(p.google_image_requests=p.google_image_requests||[]).push(kb)}};}).call(this);
