export const SET_WINDOW_ID = "SET_WINDOW_ID";
export const SET_FULL_SCREENBAR = "SET_FULL_SCREENBAR";
export const SET_START_GLOBAL_SEARCH = "SET_START_GLOBAL_SEARCH";
export const SET_SYSTEM_MINIMIZE_LIST = "SET_SYSTEM_MINIMIZE_LIST";
export const SET_TABABR_NAVIGATION = "SET_TABABR_NAVIGATION"
