export const SET_WINDOW_ID = "SET_WINDOW_ID";
export const SET_FULL_SCREENBAR = "SET_FULL_SCREENBAR";
export const SET_START_GLOBAL_SEARCH = "SET_START_GLOBAL_SEARCH";
export const SET_TABABR_MINIMIZE = "SET_TABABR_MINIMIZE";
export const SET_TABABR_NAVIGATION = "SET_TABABR_NAVIGATION";
export const SET_SYSTEM_CONFIG = "SET_SYSTEM_CONFIG";
