export const initPageConfig = [
    {
        type_name:"Favorites",
        id:1,
        list:[
            {
                img_url:"/src/assets/images/safari-img/blogs.png",
                name:"Blogs",
                web_url:"https://www.huangguangfa.cn"
            },
            {
                img_url:"/src/assets/images/safari-img/juejin.png",
                name:"技术掘金",
                web_url:"https://juejin.cn/user/1292681404747000/posts"
            },
            {
                img_url:"/src/assets/images/safari-img/blogs.png",
                name:"fcw-ui",
                web_url:"http://fcwui.huangguangfa.cn/#/fcw-ui"
            },
            {
                img_url:"/src/assets/images/safari-img/bing.png",
                name:"必应",
                web_url:"https://www.bing.com/"
            },
            {
                img_url:"/src/assets/images/safari-img/bilibili.png",
                name:"哔哩哔哩",
                web_url:"https://www.bilibili.com"
            },
            {
                img_url:"/src/assets/images/safari-img/nodejs.jpeg",
                name:"NodeJS",
                web_url:"https://nodejs.org/docs/latest-v15.x/api/"
            }
        ]
    }
]